### ISSUE TITLE
can't import fn_temp_dir when running pytest mcmodels

### ISSUE THREAD

**Issue by ChristianNitzsche** [AllenInstitute/mouse_connectivity_models#38]
Hi,

I tried to install the package, which seemed fine in the first place. But when trying 'pytest mcmodels' i get the following error:

____________________________ ERROR collecting mcmodels/core/tests/test_voxel_model_api.py _____________________________
ImportError while importing test module 'C:\Users\Christian\Desktop\Projekte\mouse_connectivity_models\mcmodels\core\tests\test_voxel_model_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mcmodels\core\tests\test_voxel_model_api.py:9: in <module>
from allensdk.test_utilities.temp_dir import fn_temp_dir
E   ImportError: cannot import name 'fn_temp_dir' from 'allensdk.test_utilities.temp_dir' (C:\Users\Christian\Anaconda3\lib\site-packages\allensdk\test_utilities\temp_dir.py)
___________________________ ERROR collecting mcmodels/core/tests/test_voxel_model_cache.py ____________________________
ImportError while importing test module 'C:\Users\Christian\Desktop\Projekte\mouse_connectivity_models\mcmodels\core\tests\test_voxel_model_cache.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mcmodels\core\tests\test_voxel_model_cache.py:11: in <module>
from allensdk.test_utilities.temp_dir import fn_temp_dir
E   ImportError: cannot import name 'fn_temp_dir' from 'allensdk.test_utilities.temp_dir' (C:\Users\Christian\Anaconda3\lib\site-packages\allensdk\test_utilities\temp_dir.py)

I am using:

Python 3.7.4
allensdk==0.16.3
mouse-connectivity-models==0.0.1

Is it possible, that the method fn_temp_dir was renamed into temp_dir in allensdk.test_utilities.temp_dir?

Thanks for your time
Christian

**Comment by justuskebschull** [comment]
Hey, 

I am having the identical issue as Christian, both on Windows and Linux, inside a conda virtual environment.

`$ pytest mcmodels
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /home/nomi/Documents/mouse_connectivity_models
collected 90 items / 2 errors / 88 selected                                                                                                                                      

===================================================================================== ERRORS =====================================================================================
__________________________________________________________ ERROR collecting mcmodels/core/tests/test_voxel_model_api.py __________________________________________________________
ImportError while importing test module '/home/nomi/Documents/mouse_connectivity_models/mcmodels/core/tests/test_voxel_model_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mcmodels/core/tests/test_voxel_model_api.py:9: in <module>
    from allensdk.test_utilities.temp_dir import fn_temp_dir
E   ImportError: cannot import name 'fn_temp_dir' from 'allensdk.test_utilities.temp_dir' (/home/nomi/.linuxbrew/opt/python/lib/python3.7/site-packages/allensdk/test_utilities/temp_dir.py)
_________________________________________________________ ERROR collecting mcmodels/core/tests/test_voxel_model_cache.py _________________________________________________________
ImportError while importing test module '/home/nomi/Documents/mouse_connectivity_models/mcmodels/core/tests/test_voxel_model_cache.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mcmodels/core/tests/test_voxel_model_cache.py:11: in <module>
    from allensdk.test_utilities.temp_dir import fn_temp_dir
E   ImportError: cannot import name 'fn_temp_dir' from 'allensdk.test_utilities.temp_dir' (/home/nomi/.linuxbrew/opt/python/lib/python3.7/site-packages/allensdk/test_utilities/temp_dir.py)
================================================================================ warnings summary ================================================================================
/home/nomi/.linuxbrew/opt/python/lib/python3.7/site-packages/jinja2/utils.py:485
  /home/nomi/.linuxbrew/opt/python/lib/python3.7/site-packages/jinja2/utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping

/home/nomi/.linuxbrew/opt/python/lib/python3.7/site-packages/jinja2/runtime.py:318
  /home/nomi/.linuxbrew/opt/python/lib/python3.7/site-packages/jinja2/runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================== 2 warnings, 2 error in 2.10s ==========================================================================
(allenenv) nomi@bio-h4tmkb2:~/Documents/mouse_connectivity_models$ ls
`

**Comment by nbingo** [comment]
@ChristianNitzsche Hey, I had the same error and I think I found the source of the error. Try changing the files 
```
/mcmodels/mouse_connectivity_models/mcmodels/core/tests/test_voxel_model_api.py
/mcmodels/mouse_connectivity_models/mcmodels/core/tests/test_voxel_model_cache.py
```
to the ones that I have attached here. I think the developers possibly have a different version of allenSDK and there are broken dependencies in the publicly available version.

[Archive.zip](https://github.com/AllenInstitute/mouse_connectivity_models/files/3827552/Archive.zip)

**Comment by kharris** [comment]
Thanks @nbingo ... if you think the tests need to be updated, please submit a pull request and we can try integrating your fixes.

**Comment by nbingo** [comment]
@kharris Just created the PR!

**Comment by DrJigsaw** [comment]
Thank you @nbingo and @kharris! @ChristianNitzsche, @justuskebschull I'm going to leave this issue open for a few days in case the error is not corrected for you. Please let us know if the issue is not resolved.

**Comment by kharris** [comment]
I started from a fresh clone of this module on python 3.7, newest version of allensdk, and it passes the tests.
