### ISSUE TITLE
Normalized connection density from PIL (Thalamus) to Isocortex

### ISSUE THREAD

**Issue by ronaldonunes** [AllenInstitute/mouse_connectivity_models#59]
Hi

I am trying to create a corticothalamic connectome, however I noticed that the normalized connection density from the thalamic area PIL to any area on Isocortex in NaN. Do you know how I can solve this?

**Comment by kamdh** [comment]
Some of the small thalamic areas have poor data and coverage by experiments. Looking at the http://connectivity.brain-map.org/ injections into PIL, all but 1 are with Cre-specific viruses. One experiment (http://connectivity.brain-map.org/projection/experiment/cortical_map/127396051) was performed with the wildtype strain but was poorly localized to the PIL region.

Long story short, I believe the algorithm has filtered out this area because the data are not there to reliably estimate connection density. The thalamus data are some of the least reliable, as noted in our paper.
